[package]
name = "azure_work"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
configuration = { path = "../configuration" }
azure_work_lib = { path = "../azure_work_lib" }